/* Script 05: Data Quality Validation - repeatable validation suite. */
SET search_path TO jdcom_analysis, public;
SELECT COUNT(*) AS total_rows FROM jdcom_analysis.customer_interactions; -- Expected 320132
SELECT COUNT(DISTINCT candidate_record_id) AS unique_candidate_records,COUNT(DISTINCT query_record_id) AS unique_query_records,COUNT(DISTINCT product_id) AS unique_products,COUNT(DISTINCT brand_id) AS unique_brands,COUNT(DISTINCT category_level_4_id) AS unique_categories,COUNT(DISTINCT shop_id) AS unique_shop_ids FROM jdcom_analysis.customer_interactions;
-- Expected: 237814 | 110393 | 237814 | 47757 | 4777 | 78976
SELECT interaction_label,interaction_type,COUNT(*) AS interaction_count,ROUND(COUNT(*)*100.0/SUM(COUNT(*)) OVER(),2) AS percentage_of_interactions FROM jdcom_analysis.customer_interactions GROUP BY interaction_label,interaction_type ORDER BY interaction_label;
-- Expected counts: 223909 | 75407 | 20816
SELECT COUNT(*) AS inconsistent_records FROM jdcom_analysis.customer_interactions WHERE (interaction_label=1 AND (interaction_type<>'Click' OR added_to_cart_or_purchased<>0 OR purchased<>0)) OR (interaction_label=2 AND (interaction_type<>'Add to Cart' OR added_to_cart_or_purchased<>1 OR purchased<>0)) OR (interaction_label=3 AND (interaction_type<>'Purchase' OR added_to_cart_or_purchased<>1 OR purchased<>1)); -- Expected 0
SELECT COUNT(*) FILTER(WHERE query IS NULL) AS missing_queries,COUNT(*) FILTER(WHERE interaction_label IS NULL) AS missing_interaction_labels,COUNT(*) FILTER(WHERE candidate_record_id IS NULL) AS missing_candidate_record_ids,COUNT(*) FILTER(WHERE query_record_id IS NULL) AS missing_query_record_ids,COUNT(*) FILTER(WHERE product_id IS NULL) AS missing_product_ids,COUNT(*) FILTER(WHERE product_name_tokens IS NULL) AS missing_product_name_tokens,COUNT(*) FILTER(WHERE brand_id IS NULL) AS missing_brand_ids,COUNT(*) FILTER(WHERE category_level_4_id IS NULL) AS missing_category_ids,COUNT(*) FILTER(WHERE shop_id IS NULL) AS missing_shop_ids,COUNT(*) FILTER(WHERE interaction_type IS NULL) AS missing_interaction_types,COUNT(*) FILTER(WHERE added_to_cart_or_purchased IS NULL) AS missing_cart_purchase_flags,COUNT(*) FILTER(WHERE purchased IS NULL) AS missing_purchase_flags FROM jdcom_analysis.customer_interactions; -- Expected all 0
SELECT COUNT(*)-COUNT(DISTINCT ROW(query,interaction_label,candidate_record_id,query_record_id,product_id,product_name_tokens,brand_id,category_level_4_id,shop_id,interaction_type,added_to_cart_or_purchased,purchased)) AS exact_duplicate_rows FROM jdcom_analysis.customer_interactions; -- Expected 16575; retained intentionally
SELECT COUNT(*) FILTER(WHERE shop_id=-1) AS unidentified_shop_records,COUNT(*) FILTER(WHERE shop_id<>-1) AS identified_shop_records,ROUND(COUNT(*) FILTER(WHERE shop_id=-1)*100.0/COUNT(*),2) AS unidentified_shop_percent FROM jdcom_analysis.customer_interactions; -- Expected 1776 | 318356 | 0.55%
SELECT COUNT(*) AS total_interactions,COUNT(*) FILTER(WHERE interaction_label=1) AS clicks,COUNT(*) FILTER(WHERE interaction_label=2) AS cart_additions,COUNT(*) FILTER(WHERE interaction_label=3) AS purchases,ROUND(COUNT(*) FILTER(WHERE interaction_label=3)*100.0/COUNT(*),2) AS purchase_share_percent FROM jdcom_analysis.customer_interactions; -- Expected 320132 | 223909 | 75407 | 20816 | 6.5%
SELECT 'category' AS view_name,SUM(total_interactions),SUM(clicks),SUM(cart_additions),SUM(purchases) FROM jdcom_analysis.category_performance UNION ALL SELECT 'brand',SUM(total_interactions),SUM(clicks),SUM(cart_additions),SUM(purchases) FROM jdcom_analysis.brand_performance UNION ALL SELECT 'product',SUM(total_interactions),SUM(clicks),SUM(cart_additions),SUM(purchases) FROM jdcom_analysis.product_performance UNION ALL SELECT 'query',SUM(total_interactions),SUM(clicks),SUM(cart_additions),SUM(purchases) FROM jdcom_analysis.query_performance; -- Each expected full totals 320132 | 223909 | 75407 | 20816
SELECT SUM(total_interactions),SUM(clicks),SUM(cart_additions),SUM(purchases) FROM jdcom_analysis.shop_performance; -- Expected identified totals 318356 | 222676 | 74929 | 20751
